In [95]:
from sklearn.datasets import load_iris
iris = load_iris()

X = iris.data
y = iris.target

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=5)

X2 = iris.data
y2 = iris.target

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.6, random_state=5)

X3 = iris.data
y3 = iris.target

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=5)


In [96]:
# Fitting SVC Classification to the Training set with linear kernel
from sklearn.svm import SVC
svcclassifier = SVC(kernel = 'linear', random_state = 43)
svcclassifier2 = SVC(kernel = 'poly', random_state = 8)
svcclassifier3 = SVC(kernel = 'rbf', random_state = 0)


svcclassifier.fit(X_train, y_train) 
svcclassifier2.fit(X_train2, y_train2) 
svcclassifier3.fit(X_train3, y_train3) 

# Predicting the Test set results
y_pred = svcclassifier.predict(X_test)
y_pred2 = svcclassifier2.predict(X_test)
y_pred3 = svcclassifier3.predict(X_test)

print(y_pred)
print(y_pred2)
print(y_pred3)



[1 2 2 0 2 1 0 2 0 1 1 2 2 2 0 0 2 2 0 0 1 2 0 1 1 2 1 1 1 2 0 1 1 0 1 0 0
 2 0 2 2 1 0 0 1 2 1 2 2 0 2 0 0 0 0 1 1 1 1 2 1 2 2 1 0 1 0 1 2 1 2 1 2 1
 1]
[1 2 2 0 2 1 0 2 0 1 1 2 2 2 0 0 2 2 0 0 1 2 0 1 1 2 1 1 1 2 0 1 1 0 1 0 0
 2 0 2 2 1 0 0 1 2 1 2 2 0 2 0 0 0 0 1 1 1 1 2 1 2 2 1 0 1 0 1 2 1 2 1 2 1
 1]
[1 2 2 0 2 1 0 2 0 1 1 2 2 2 0 0 2 2 0 0 1 2 0 1 1 2 1 1 1 2 0 1 1 0 1 0 0
 2 0 2 2 1 0 0 1 2 1 2 2 0 2 0 0 0 0 1 1 1 1 2 1 2 2 1 0 1 0 2 2 1 2 1 2 1
 1]


In [97]:
#lets see the actual and predicted value side by side
y_compare = np.vstack((y_test,y_pred)).T
y_compare[:5,:]

#lets see the actual and predicted value side by side
y_compare2 = np.vstack((y_test,y_pred2)).T
y_compare[:5,:]

#lets see the actual and predicted value side by side
y_compare3 = np.vstack((y_test,y_pred3)).T
y_compare[:5,:]

array([[1, 1],
       [2, 2],
       [2, 2],
       [0, 0],
       [2, 2]])

In [98]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

cm2 = confusion_matrix(y_test, y_pred2)
print(cm)

cm3 = confusion_matrix(y_test, y_pred3)
print(cm)

[[22  0  0]
 [ 0 28  1]
 [ 0  0 24]]
[[22  0  0]
 [ 0 28  1]
 [ 0  0 24]]
[[22  0  0]
 [ 0 28  1]
 [ 0  0 24]]


In [99]:
#finding accuracy from the confusion matrix.
a = cm.shape
corrPred = 0
falsePred = 0

for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrPred +=cm[row,c]
        else:
            falsePred += cm[row,c]
print('Correct predictions: ', corrPred)
print('False predictions', falsePred)
kernelLinearAccuracy = corrPred/(cm.sum())
print ('Accuracy of the SVC Clasification is: ', corrPred/(cm.sum()))  


#finding accuracy from the confusion matrix.
a = cm.shape
corrPred = 0
falsePred = 0

for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrPred +=cm2[row,c]
        else:
            falsePred += cm2[row,c]
print('Correct predictions: ', corrPred)
print('False predictions', falsePred)
kernelLinearAccuracy = corrPred/(cm2.sum())
print ('Accuracy of the SVC Clasification is: ', corrPred/(cm2.sum()))  


#finding accuracy from the confusion matrix.
a = cm.shape
corrPred = 0
falsePred = 0

for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrPred +=cm3[row,c]
        else:
            falsePred += cm3[row,c]
print('Correct predictions: ', corrPred)
print('False predictions', falsePred)
kernelLinearAccuracy = corrPred/(cm3.sum())
print ('Accuracy of the SVC Clasification is: ', corrPred/(cm3.sum()))  

Correct predictions:  74
False predictions 1
Accuracy of the SVC Clasification is:  0.9866666666666667
Correct predictions:  74
False predictions 1
Accuracy of the SVC Clasification is:  0.9866666666666667
Correct predictions:  73
False predictions 2
Accuracy of the SVC Clasification is:  0.9733333333333334
